trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguraion: 'Realease'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
